### ISSUE TITLE
INVALID_ARGUMENT from CreateMicroVM when using Bloom/Node Client 

### ISSUE THREAD

**Issue by richardcase** [weaveworks-liquidmetal/flintlock#468]
**What happened:**
When using BloomRPC or Node's [grpc/proto-loader](https://www.npmjs.com/package/@grpc/proto-loader) to call **CreateMicroVM** the following errors are returned:

From BloomRPC:

```json
{
  "error": "3 INVALID_ARGUMENT: an error occurred when attempting to validate the request: validation failures found: Key: 'MicroVM.Spec.RootVolume.MountPoint' Error:Field validation for 'MountPoint' failed on the 'required' tag"
}
```

And Node:

```json
Error: 3 INVALID_ARGUMENT: an error occurred when attempting to validate the request: validation failures found: Key: 'MicroVM.Spec.NetworkInterfaces[1].GuestDeviceName' Error:Field validation for 'GuestDeviceName' failed on the 'required' tag
Key: 'MicroVM.Spec.RootVolume.MountPoint' Error:Field validation for 'MountPoint' failed on the 'required' tag
    at Object.exports.createStatusError (/Users/cauld/projects/custom-tasks/ts-flintlock/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/cauld/projects/custom-tasks/ts-flintlock/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/cauld/projects/custom-tasks/ts-flintlock/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/cauld/projects/custom-tasks/ts-flintlock/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/cauld/projects/custom-tasks/ts-flintlock/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 3,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: "an error occurred when attempting to validate the request: validation failures found: Key: 'MicroVM.Spec.NetworkInterfaces[1].GuestDeviceName' Error:Field validation for 'GuestDeviceName' failed on the 'required' tag\n" +
    "Key: 'MicroVM.Spec.RootVolume.MountPoint' Error:Field validation for 'MountPoint' failed on the 'required' tag"
}
```

**What did you expect to happen:**
I expect to be able to call **CreateMicroVM** (and the other API calls) from different clients including BloomRPC and NodeJS.

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
This sounds like `MountPoint` isn't being set. I'm currently creating a test node app.

**Comment by richardcase** [comment]
I have re-created the issue and have got the same error:

```
Error: 3 INVALID_ARGUMENT: an error occurred when attempting to validate the request: validation failures found: Key: 'MicroVM.Spec.RootVolume.MountPoint' Error:Field validation for 'MountPoint' failed on the 'required' tag
    at Object.callErrorFromStatus (/home/richard/code/ww/flintlock_nodejstest/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/richard/code/ww/flintlock_nodejstest/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/home/richard/code/ww/flintlock_nodejstest/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/home/richard/code/ww/flintlock_nodejstest/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/richard/code/ww/flintlock_nodejstest/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {code: 3, details: 'an error occurred when attempting to validat…or 'MountPoint' failed on the 'required' tag', metadata: Metadata, stack: 'Error: 3 INVALID_ARGUMENT: an error occurred …tions (internal/process/task_queues.js:77:11)', message: '3 INVALID_ARGUMENT: an error occurred when a…or 'MountPoint' failed on the 'required' tag'}
```

This is because there is no mount point specified on the create request:

```json
    root_volume: {
        id: "root",
        is_read_only: "false",
        //mount_point: "/",
        source: {
            container_source: "ghcr.io/weaveworks-liquidmetal/capmvm-kubernetes:1.23.5"
        }
    },
```

**Comment by Callisto13** [comment]
As a related FYI, just in case you were thinking about it: I remember having a conversation around whether we should default the `root_volume` mount point to `"/"` and think we ended up saying that we... shouldn't? There is a thread somewhere... I hope.

**Comment by richardcase** [comment]
@Callisto13  this is the dicussion: https://github.com/weaveworks-liquidmetal/flintlock/discussions/241#discussioncomment-1630857

**Comment by Callisto13** [comment]
I think if we default this, just to be totally cautious, we should add a check on other volumes that they are not being mounted at `"/"`, wdyt?

Admittedly the risk is small, but it is exactly the kind of irritating little thing which could come back to annoy us

**Comment by richardcase** [comment]
Sounds good, i will make that change.

**Comment by richardcase** [comment]
We have decided to remove **MountPoint** from flintlock for the time being as its not being used anywhere and so it seems weird that we require it.

**Comment by richardcase** [comment]
This has been fixed to closing
